// preact/src/Tile.tsx
import { Component, createElement } from 'preact';
import { TileComponentProps } from 'sample-cross-fx';

export class Tile extends Component<TileComponentProps> {
  state = {
    count: 0,
  };

  private increment = () => this.setState({ count: this.state.count + 1 });

  private decrement = () => this.setState({ count: this.state.count - 1 });

  render() {
    const { piral, rows, columns } = this.props;
    const { count } = this.state;
    const { PreactExtension } = piral;

    return createElement(
      'div',
      {
        class: 'tile',
      },
      createElement('h3', {}, `Preact: ${count}`),
      createElement(
        'p',
        {},
        `${rows} rows and ${columns} columns `,
        createElement(PreactExtension, {
          name: 'smiley',
        }),
      ),
      createElement(
        'button',
        {
          onClick: this.increment,
        },
        '+',
      ),
      createElement(
        'button',
        {
          onClick: this.decrement,
        },
        '-',
      ),
    );
  }
}

// solid/src/Tile.tsx
import { createState, Component } from 'solid-js';
import { TileComponentProps } from 'sample-cross-fx';

export const Tile: Component<TileComponentProps> = ({ piral, rows, columns }) => {
  const [state, setState] = createState({ count: 0 });
  const { SolidExtension } = piral;

  return (
    <div class="tile">
      <h3>Solid {state.count}</h3>
      <p>
        {rows} rows and {columns} columns <SolidExtension name="smiley" />
      </p>
      <button onClick={() => setState({ count: state.count + 1 })}>+</button>
      <button onClick={() => setState({ count: state.count - 1 })}>-</button>
    </div>
  );
};
