// million/src/Tile.tsx
import { useState, createElement } from 'million/react';
import { TileComponentProps } from 'sample-cross-fx';
import { MillionExtension } from 'piral-million/convert';

export const Tile = ({ rows, columns }: TileComponentProps) => {
  const [count, setCount] = useState(0);
  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);

  return (
    <div className="tile">
      <h3>Million {count}</h3>
      <p>
        {rows} rows and {columns} columns <MillionExtension name="smiley" />
      </p>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
    </div>
  );
};

// solid/src/Tile.tsx
import { createSignal, Component } from 'solid-js';
import { TileComponentProps } from 'sample-cross-fx';

export const Tile: Component<TileComponentProps> = ({ piral, rows, columns }) => {
  const [getCount, setCount] = createSignal(0);
  const { SolidExtension } = piral;

  return (
    <div class="tile">
      <h3>Solid {getCount()}</h3>
      <p>
        {rows} rows and {columns} columns <SolidExtension name="smiley" />
      </p>
      <button onClick={() => setCount(getCount() + 1)}>+</button>
      <button onClick={() => setCount(getCount() - 1)}>-</button>
    </div>
  );
};
